### ISSUE TITLE
Should the indexer be part of a language server or a standalone tool

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/lsif-node#6]
Or both.

**Comment by DanTup** [comment]
@dbaeumer Slightly related - When is the tool expected to run and where will the index be stored?

I think in a demo video it was shown that GH PRs in Code could be navigated using LSIF data without having the language extension installed locally. Where is the LSIF data in that case coming from? It seems unlikely that a user would build an LSIF index and commit it in their repo with their pull request.

(I ask here, because I think where it's being run and by who may influence the answer to this question)

**Comment by dbaeumer** [comment]
@DanTup sorry for the late answer. I think this depends on what you want to do with the dump. We have now tooling to import it into a local SQLite DB and browser it basically offline. So this use case is for local. For things in GitHub it will very likely run in the CLI pipeline.

**Comment by dbaeumer** [comment]
We collect good experiences with having this as a standalone tool. Java and others went down the same path. I would keep it that way for now.
