### ISSUE TITLE
[lsif-util] Visualize output is invalid dot format

### ISSUE THREAD

**Issue by arjunattam** [microsoft/lsif-node#70]
Running `visualize` and passing output to graphviz is throwing errors in some cases with this particular LSIF file: [temp.txt](https://github.com/microsoft/lsif-node/files/3507808/temp.txt)

Some vertex ids don't work:

```
lsif-util visualize temp.txt --id 1163 --distance 2 | dot -Tpng -o image.png 
Error: <stdin>: syntax error in line 7 near '\'
```

Some vertex ids work:

```
lsif-util visualize temp.txt --id 1168 --distance 2 | dot -Tpng -o image.png 
```

```
lsif-util --version
0.2.15
```

**Comment by arjun27** [comment]
My guess is that this is happening due to hoverResult values that look like 

```
"value":"(property) Markdown.type: \"markdown\""
```

If this is the case, we can consider removing `value` from the graphviz output. In the ways I use this tool, I hardly refer to the `value`. Can open this for more feedback

**Comment by jumattos** [comment]
This seems to be related to the work I am planning to do to enhance visualization. The idea would be treating each kind of vertex in a special way and only print what's relevant (instead of printing all properties). Unfortunately, it's not a high priority right now. Let me know if you need to find a workaround earlier.
